In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/Nigerian_Car_Prices.csv")

In [3]:
data.head()

,Unnamed: 0,Make,Year of manufacture,Condition,Mileage,Engine Size,Fuel,Transmission,Price,Build
0,0,Toyota,2007.0,Nigerian Used,166418.0,2400.0,Petrol,Automatic,"3,120,000",NaN
1,1,Lexus,NaN,NaN,138024.0,NaN,NaN,Automatic,"5,834,000",NaN
2,2,Mercedes-Benz,2008.0,Nigerian Used,376807.0,3000.0,Petrol,Automatic,"3,640,000",NaN
3,3,Lexus,NaN,NaN,213362.0,NaN,NaN,Automatic,"3,594,000",NaN
4,4,Mercedes-Benz,NaN,NaN,106199.0,NaN,NaN,Automatic,"8,410,000",NaN

In [4]:
data.describe()

        Unnamed: 0  Year of manufacture       Mileage    Engine Size
count  4095.000000          3617.000000  4.024000e+03    3584.000000
mean   2047.000000          2007.898535  1.825337e+05    3274.976562
std    1182.269005             4.300126  2.109233e+05    7693.489588
min       0.000000          1992.000000  1.000000e+00       3.000000
25%    1023.500000          2005.000000  1.020640e+05    2000.000000
50%    2047.000000          2008.000000  1.613525e+05    2500.000000
75%    3070.500000          2011.000000  2.319522e+05    3500.000000
max    4094.000000          2021.000000  9.976050e+06  371000.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4095 entries, 0 to 4094
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           4095 non-null   int64
 1   Make                 4095 non-null   object
 2   Year of manufacture  3617 non-null   float64
 3   Condition            3616 non-null   object
 4   Mileage              4024 non-null   float64
 5   Engine Size          3584 non-null   float64
 6   Fuel                 3607 non-null   object
 7   Transmission         4075 non-null   object
 8   Price                4095 non-null   object
 9   Build                1127 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 320.0+ KB

In [6]:
data.drop("Unnamed: 0", axis = 1, inplace = True)

In [7]:
data.head()

,Make,Year of manufacture,Condition,Mileage,Engine Size,Fuel,Transmission,Price,Build
0,Toyota,2007.0,Nigerian Used,166418.0,2400.0,Petrol,Automatic,"3,120,000",NaN
1,Lexus,NaN,NaN,138024.0,NaN,NaN,Automatic,"5,834,000",NaN
2,Mercedes-Benz,2008.0,Nigerian Used,376807.0,3000.0,Petrol,Automatic,"3,640,000",NaN
3,Lexus,NaN,NaN,213362.0,NaN,NaN,Automatic,"3,594,000",NaN
4,Mercedes-Benz,NaN,NaN,106199.0,NaN,NaN,Automatic,"8,410,000",NaN

In [8]:
data["Make"].value_counts()

Toyota           1469
Lexus             464
Mercedes-Benz     436
Honda             428
Ford              197
Hyundai           179
Nissan            173
Kia                90
Land Rover         74
Volkswagen         64
Mazda              63
BMW                63
Acura              56
Infiniti           41
Chevrolet          40
Peugeot            36
Mitsubishi         23
Pontiac            22
Volvo              22
Suzuki             21
Dodge              17
Audi               14
Opel               12
Jaguar             11
Jeep               11
Porsche             9
Renault             8
Chrysler            7
Fiat                6
GMC                 5
Changan             4
Lincoln             4
Skoda               3
Hummer              2
Buick               2
JAC                 2
Citroen             2
Isuzu               2
Mini                2
MG                  2
Rover               1
Bentley             1
Seat                1
SsangYong           1
Cadillac            1
Saturn              1
Tata                1
Foton               1
Daihatsu            1
Name: Make, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data["Make"] = encoder.fit_transform(data["Make"])